# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YjMwY2FhNjFmYzk5MzM5NDE1MGI5MmRkNzEwMmI4YWRjMDhjZmQ1ODc4M2JjOWQwY2E0NDM1YjU3MzU0OTAyMzQxMjc1YTNkMmUzNjA4NjIzZGM1YmI0NGFiNThhNTc5M2I2ZTRmOWY4NzJlMDY0MTA2YmVlZTc3MTBlZTU4ODY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
